rule all:
    input:
        "data/output.txt"


rule make_output:
    output:
        "data/output.txt"
    run:
        """
        with open(output[0], 'w') as f:
            f.write("This is a Snakemake demo output file.")
        """
        