name: CI/CD

on:
  pull_request:
    branches: [main, master, dev]
  push:
    branches: [main, master, dev]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy
          npm install -g prettier

      - name: Prettier Check
        run: prettier --check "vue-frontend/**/*.{js,vue,css,html}"

      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: terraform

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Validate HTML
        run: tidy -qe vue-frontend/index.html

  deploy:
    needs: lint
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      TF_VAR_cdn_url: ${{ secrets.CDN_URL }}
      TF_VAR_spotify_client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
      TF_VAR_spotify_client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::832242454463:role/ZappaUserRole
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
