name: CI/CD

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      
      - name: Run Tests
        run: |
          pytest tests/
  
  build-artifact:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies to venv
        run: |
          python -m venv env
          source env/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Build Artifact
        run: |
          source env/bin/activate
          zappa package dev -o ctbus_site.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "ctbus_site_${{ github.run_id }}"
          path: ./ctbus_site.zip

  dev-deploy:
    needs: build-artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: "ctbus_site_${{ github.run_id }}"
      
      - name: Deploy to Dev
        run: |
          source env/bin/activate
          zappa update dev --zip "ctbus_site_${{ github.run_id }}.zip" --json

  test-deployment:
    needs: dev-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          echo "GOT TO HERE"