name: CI/CD

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Lint Code
        run: |
          black . --check

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      
      - name: Run Tests
        run: |
          pytest tests/unit/ tests/integration/
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
  
  build-artifact:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies to venv
        run: |
          python -m venv env
          source env/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install setuptools
      
      - name: Build Artifact
        run: |
          source env/bin/activate
          zappa package dev -o ctbus_site.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ctbus_site
          path: ./ctbus_site.zip
          retention-days: 1

  dev-deploy:
    needs: build-artifact
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Zip
        uses: actions/download-artifact@v4
        with:
          name: ctbus_site
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::832242454463:role/ZappaUserRole
          aws-region: us-east-1
      
      - name: Setup AWS Profile
        run: |
          aws configure set region us-east-1 --profile default
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile default
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile default
          aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile default
      
      - name: Deploy to Dev
        run: |
          zappa update dev --zip ctbus_site.zip --json

      - name: Dump Logs
        if: always()
        run: |
          sleep 30
          zappa tail dev --json --since 10m --disable-keep-open

  test-deployment:
    needs: dev-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt update
          sudo apt install -y chromium-browser

          wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          tar -xvzf geckodriver*
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/

      - name: Install Pip Dependencies
        run: |
          pip install requests webdriver-manager selenium pytest

      - name: Run PyTest
        run: |
          pytest -rA tests/e2e/

  linkcheck-deployment:
    needs: dev-deploy
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/linkchecker/linkchecker:latest

    steps:
      - name: Run check
        run: linkchecker https://cjg5wanye9.execute-api.us-east-1.amazonaws.com/dev/
  
  zap-deployment:
    needs: dev-deploy
    runs-on: ubuntu-latest

    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://cjg5wanye9.execute-api.us-east-1.amazonaws.com/dev/'
  
  unsign-deployment:
    needs: dev-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          pip install flask-unsign
      
      - name: Unsign Flask Session
        run: |
          flask-unsign --decode --server "https://cjg5wanye9.execute-api.us-east-1.amazonaws.com/dev/" || true

  web-accessibility-eval:
    needs: dev-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Pass
        run: echo "Pass"
      # - name: Web Accessibility Eval
      #   uses: a11ywatch/github-action@v2.1.10
      #   with:
      #     WEBSITE_URL: https://cjg5wanye9.execute-api.us-east-1.amazonaws.com/dev/
      #     SITE_WIDE: false
      #     SUBDOMAINS: false
      #     TLD: false
      #     SITEMAP: true
      #     FAIL_ERRORS_COUNT: 15
      #     LIST: true
      #     FIX: false
      #     UPGRADE: false
      #     UPLOAD: true
      #   env:
      #     DEFAULT_RUNNERS: htmlcs,axe
      #     PAGEMIND_IGNORE_WARNINGS: true
      #     AI_DISABLED: false

  remove-artifact:
    needs: [build-artifact, dev-deploy, test-deployment, linkcheck-deployment, zap-deployment, unsign-deployment, web-accessibility-eval]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest

    steps:
      - name: Remove Artifact
        uses: geekyeggo/delete-artifact@v5
        with:
            name: ctbus_site
            failOnError: false

  prod-deploy:
    needs: [test-deployment, linkcheck-deployment, zap-deployment, unsign-deployment, web-accessibility-eval, lint]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Zip
        uses: actions/download-artifact@v4
        with:
          name: ctbus_site
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::832242454463:role/ZappaUserRole
          aws-region: us-east-1
      
      - name: Setup AWS Profile
        run: |
          aws configure set region us-east-1 --profile default
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile default
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile default
          aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile default
      
      - name: Deploy to Prod
        run: |
          zappa update prod --zip ctbus_site.zip --json

      - name: Dump Logs
        if: always()
        run: |
          sleep 30
          zappa tail prod --json --since 10m --disable-keep-open